language: python
cache:
    pip: true
services:
    - postgresql
addons:
    # 9.4 supports JSONB fields, but 9.5 adds the ability to do
    # CREATE INDEX IF NOT EXISTS
    postgresql: "9.5"

before_install:
  - psql --version
install:
  - pip install tox
  - pip install python-coveralls
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
script:
  - tox

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-1.10 }
    - { python: 2.7, env: TOXENV=py27-1.11 }
    - { python: 3.4, env: TOXENV=py34-1.10 }
    - { python: 3.4, env: TOXENV=py34-1.11 }
    - { python: 3.4, env: TOXENV=py34-2.0 }
    - { python: 3.5, env: TOXENV=py35-1.10 }
    - { python: 3.5, env: TOXENV=py35-1.11 }
    - { python: 3.5, env: TOXENV=py35-2.0 }
    - { python: 3.5, env: TOXENV=py35-master }
    - { python: 3.6, env: TOXENV=py36-2.0 }
    - { python: 3.6, env: TOXENV=py36-master }
    - { python: 3.5, env: TOXENV=isort }
    - { python: 3.5, env: TOXENV=py27-migrate }
    - { python: 3.5, env: TOXENV=py35-migrate }
    - { python: 2.7, env: TOXENV=docs }

  # we allow failures for versions which are not yet released:
  allow_failures:
      - env: TOXENV=py35-master
      - env: TOXENV=py36-master

after_success:
    coveralls
