language: python
cache:
    pip: true
services:
    - postgresql
addons:
    # 9.4 supports JSONB fields, but 9.5 adds the ability to do
    # CREATE INDEX IF NOT EXISTS
    postgresql: "9.5"
    apt:
       packages:
           - enchant
           - myspell-en-us

before_install:
  - psql --version
install:
  - pip install tox python-coveralls
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
script:
  - tox

matrix:
  include:
    - { python: 3.5, env: TOXENV=py35-2.1 }
    - { python: 3.5, env: TOXENV=py35-2.2 }
    - { python: 3.6, env: TOXENV=py36-2.1 }
    - { python: 3.6, env: TOXENV=py36-2.2 }
    - { python: 3.6, env: TOXENV=py36-3.0 }
    - { python: 3.6, env: TOXENV=py36-master }
    - { python: 3.7, env: TOXENV=py37-2.1 }
    - { python: 3.7, env: TOXENV=py37-2.2 }
    - { python: 3.7, env: TOXENV=py37-3.0 }
    - { python: 3.7, env: TOXENV=py37-master }
    - { python: 3.7, env: TOXENV=flake8 }
    - { python: 3.7, env: TOXENV=isort }
    - { python: 3.7, env: TOXENV=migrate }
    - { python: 3.7, env: TOXENV=docs }
    - { python: 3.7, env: TOXENV=black}

  # we allow failures for versions which are not yet released:
  allow_failures:
      - env: TOXENV=py36-master
      - env: TOXENV=py37-master
      - env: TOXENV=py38-master

after_success:
    coveralls
